### ISSUE TITLE
remove hyper dev dependency

### ISSUE THREAD

**Issue by viperscape** [BurntSushi/chan#1]
Is it possible to remove hyper from the dev dependencies?
Hyper includes openssl which is a pain to build on Windows

Thanks

```
// Cargo.toml
[dev-dependencies]
hyper = { version = "*" }
```

**Comment by BurntSushi** [comment]
Yeah, I can do that. But I'll have to get rid of the `web.rs` example. (I don't think dev dependencies are subject to features.)

**Comment by viperscape** [comment]
I didn't realize dev dependencies are used during a benchmark, which is why I ask since I wanted to see what kind of performance it actually had on a modern i7. Instead do you mind publishing your results somewhere? It'd be nice if rust separated out examples with a cargo feature. Something like `cargo example` would be nice

**Comment by BurntSushi** [comment]
OK, I've added the output of running `cargo bench`: https://github.com/BurntSushi/chan/blob/master/BENCHMARKS.md

Please keep in mind: http://burntsushi.net/rustdoc/chan/#warning:-performance

**Comment by viperscape** [comment]
Great thanks! I'll close this now, keeping the web.rs example is important
