### ISSUE TITLE
Using chan_select! requires values to be 'static

### ISSUE THREAD

**Issue by dflemstr** [BurntSushi/chan#14]
Using `chan_select!` forces values to be static for no apparent reason.  At the time of writing, here: https://github.com/BurntSushi/chan/blob/12919f83a8990ed391c6a0c334d04e2184410e5a/src/select.rs#L239

This is very inconvenient while using a scoped thread pool where threads communicate with each other via pointers into a big buffer. All of the normal channel operations work fine, except `chan_select!`

**Comment by BurntSushi** [comment]
Does removing the `'static` bound actually work for you?

I can't remember why I specifically added that bound.

**Comment by dflemstr** [comment]
I filed this issue 2am my time so I didn't have time to create a fork etc to try it out :) I'll do that when I get time.

**Comment by dflemstr** [comment]
Yep, removing it works for me! I can create a PR
