### ISSUE TITLE
Select integration with std lib mpsc api

### ISSUE THREAD

**Issue by softprops** [BurntSushi/chan#18]
First off that you so much for this crate it provides everything im missing from the std lib. Ive recently ran into some pain points though. In particular Im interfacting with other crates that use the std lib's mpsc api. Are there suggested patterns for adapting. What I really want is a select api that's compatible with stable rust.

**Comment by BurntSushi** [comment]
Thanks for the kind words!

I don't see how your request is possible. Could you perhaps suggest a straw man implementation path?

It might help if you stated the specific problem you are trying to solve.

**Comment by softprops** [comment]
Sure. I'm working on integrating the notify crate into my bazel build workflow https://github.com/meetup/rebazel/blob/master/src/main.rs#L131.

The notify crate requires an mpsc sender.

Ideally I could have two watchers one for each kind of file I'm watching: build definitions which define sources and one for the source files them selves. Atm my program only has one watcher for both but then I have to try to infer by file name what kind of file changed when any file changed 

https://github.com/meetup/rebazel/blob/master/src/main.rs#L140

That feels fragile. This sounded like a perfect case for chans select macro where I may have two watchers and and two recievers but i cant use it with the buillt in mpsc recievers with Chan's select. 

I was wondering if there were any suggestions for patterns on adapting those to chan interfaces or visa versa

**Comment by BurntSushi** [comment]
The "select" functionality in this crate is *deeply coupled* to the channels themselves. Is it possible to design a higher level interface and try to unify all possible channel implementation? I'm honestly not sure. I wrote this code a long time ago and I don't have a good feel for the essential challenges in that task. Moreover, it feels like a very hard task, and one that I have no plans of working on. :-)

With all that said, I feel like the obvious answer to this problem might be going unnoticed. If you have a `mpsc::Sender` but you want all of your code to work with `chan` channels, then it should be straight-forward to create a `chan` channel for the `mpsc::Sender`, and then spawn a thread that reads from the `chan` channel and forwards messages to the `mpsc::Sender` channel. Rinse and repeat for each integration point.

**Comment by softprops** [comment]
That makes sense. Thanks for your input!
