### ISSUE TITLE
Allow chan_select to generate no-op None variants

### ISSUE THREAD

**Issue by mqudsi** [BurntSushi/chan#19]
I'm not sure if this is easily doable or not, but would it be possible for the `select_chan` macro to fill in no-op variants of uncovered patterns?

For example, trying to compile this results in an error `refutable pattern in local binding: ``None`` not covered`:

```rust
    chan_select! {
               msg_rx.recv() -> Some(user) => {
                   //do something with user
               }
    }
```

and it is necessary to be overly verbose:
```rust
    chan_select! {
               msg_rx.recv() -> x => {
                       if let Some(user) = x {
                           //do something with user
                        }
               }
    }
```

**Comment by BurntSushi** [comment]
You are certainly welcome to try to adapt the macro that way. I doubt I'll try myself. The macro it's quite sensitive. Have you read the documentation for it?

**Comment by BurntSushi** [comment]
This crate is now deprecated. See: https://users.rust-lang.org/t/ann-chan-is-deprecated-use-crossbeam-channel-instead/19251
