### ISSUE TITLE
Return value from `chan_select!` expression

### ISSUE THREAD

**Issue by AlexArgoAi** [BurntSushi/chan#30]
Could `chan_select!` return a value if all branches return the same type?

For instance:

```rust
let result = chan_select! {
    default => {
        None
    },
    input_a.recv() => {
        Some(true)
    },
    input_b.recv() => {
        Some(false)
    },
};
```

(Right now `chan_select!` doesn't return anything and `result` would be `()`.)

Currently a workaround is to wrap the `chan_select!` in a function and `return` in each branch.

**Comment by BurntSushi** [comment]
Unlikely, no. You might consider using crossbeam-channel instead. My plan is to end-of-life chan, but I just haven't caught up yet.

**Comment by BurntSushi** [comment]
See #25.
